import React from 'react';
import {
  Button,
  PageHeader,
  Input,
  Pagination,
  Divider,
  Switch,
} from 'antd';
import Function from 'util/Function';
import IFilter, { IFilterProps } from 'components/general/IFilter';
import { ClothingDTO } from 'fetch/wardrobe';
import TypeSelector from '../general/TypeSelector';

// The original version of these kinds of pages should be generated by a (DTO => React) code generator.

type Props = IFilterProps<ClothingDTO> & {};

type State = {
  selectedType: string,
};

export default class ArticleFilter extends React.Component<Props, State> {
  constructor(props : Props) {
    super(props);

    this.state = {
      selectedType: '',
    };
  }

  setSelectedType = (selectedType: string):void => {
    const { onChange } = this.props;

    const f = (datum: ClothingDTO):boolean => datum.clothingType === selectedType;
    onChange(f);

    this.setState({ selectedType });
  };

  render() {
    const { selectedType } = this.state;
    return (
      <div>
        <h3>Types:</h3>
        <TypeSelector
          selected={selectedType}
          onChange={
            this.setSelectedType
          }
        />
      </div>
    );
  }
}
